name: my custom workflow
on: [workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "hello world"

      - name: what_is_the_ram_size
        run: free -h

      - name: what_is_the_cpu
        run: lscpu | grep "Model name"
      - name: check_cpu_count
        run: |
          echo "Total Cores:"
          nproc
          echo "Detailed CPU Info:"
          lscpu | grep -E '^Thread\(s\) per core|^Core\(s\) per socket|^CPU\(s\):'
